/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package visual.compra;

import dao.DAOCompra;
import dao.DAOFornecedor;
import dao.DAOItensCompra;
import java.util.ArrayList;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import modelo.Compra;
import modelo.Fornecedor;
import modelo.ItensCompra;
import visual.itensCompra.CadastroItensCompra;
/**
 *
 * @author Igor
 */
public class CadastroCompra extends javax.swing.JFrame {
    private Compra compra = new Compra();
    public List<ItensCompra> listaItens = new ArrayList<>();
    public double valor = 0.0;
    /**
     * Creates new form CadastroCompra
     */
    public CadastroCompra() {
        initComponents();
        comboFornecedor.setModel(new DefaultComboBoxModel(new DAOFornecedor().consultarTodos().toArray()));
        labelValor.setText(Double.toString(valor));
        this.setLocationRelativeTo(null);
    }
    
    public void alteraValor(){
        labelValor.setText(Double.toString(valor));
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        comboFornecedor = new javax.swing.JComboBox<>();
        labelFornecedor = new javax.swing.JLabel();
        botaoIdC = new javax.swing.JButton();
        labelTagValor = new javax.swing.JLabel();
        labelValor = new javax.swing.JLabel();
        botaoCancelar = new javax.swing.JButton();
        botaoIncluir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastrar Compra");

        comboFornecedor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        labelFornecedor.setText("Fornecedor");

        botaoIdC.setText("Adicionar Itens a Compra");
        botaoIdC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoIdCActionPerformed(evt);
            }
        });

        labelTagValor.setText("Valor:");

        labelValor.setText("jLabel3");

        botaoCancelar.setText("Cancelar");
        botaoCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoCancelarActionPerformed(evt);
            }
        });

        botaoIncluir.setText("Incluir");
        botaoIncluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoIncluirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(comboFornecedor, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(botaoIncluir)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(botaoCancelar))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelFornecedor)
                            .addComponent(botaoIdC)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(labelTagValor)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(labelValor)))
                        .addGap(0, 187, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelFornecedor)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(comboFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botaoIdC)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelTagValor)
                    .addComponent(labelValor))
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botaoCancelar)
                    .addComponent(botaoIncluir))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botaoIncluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoIncluirActionPerformed
        compra.setValor(valor);
        new DAOCompra().incluir(compra);
        compra.setId(new DAOCompra().retornaUltimo());
        for(ItensCompra i : listaItens){
            i.setCompra(compra);
            new DAOItensCompra().inserir(i);
        }
    }//GEN-LAST:event_botaoIncluirActionPerformed

    private void botaoCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoCancelarActionPerformed
        this.dispose();
    }//GEN-LAST:event_botaoCancelarActionPerformed

    private void botaoIdCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoIdCActionPerformed
        compra.setValor(0.0);
        compra.setFornecedor((Fornecedor) comboFornecedor.getSelectedItem());
        CadastroItensCompra cic = new CadastroItensCompra(compra,listaItens,this);
        cic.setTitle("Adicione os Produtos");
        cic.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        cic.setLocationRelativeTo(null);
        cic.setVisible(true);
    }//GEN-LAST:event_botaoIdCActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoCancelar;
    private javax.swing.JButton botaoIdC;
    private javax.swing.JButton botaoIncluir;
    private javax.swing.JComboBox<String> comboFornecedor;
    private javax.swing.JLabel labelFornecedor;
    private javax.swing.JLabel labelTagValor;
    private javax.swing.JLabel labelValor;
    // End of variables declaration//GEN-END:variables
}
