/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package visual.itensCompra;

import visual.compra.CadastroCompra;
import javax.swing.JOptionPane;
import modelo.ItensCompra;
import dao.DAOItensCompra;
import dao.DAOCompra;
import dao.DAOProduto;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import modelo.Compra;
import modelo.Produto;
/**
 *
 * @author Igor
 */
public class CadastroItensCompra extends javax.swing.JFrame {
    private DAOItensCompra daoItensCompra = new DAOItensCompra();
    private List<ItensCompra> listaItens;
    private CadastroCompra cadCompra;
    private Compra compra = new Compra();
    
    /**
     * Creates new form CadastroItensCompra
     */
    
    public CadastroItensCompra(Compra compra, List<ItensCompra> listaItens, CadastroCompra cadCompra){
        this();
        this.compra = compra;
        this.listaItens = listaItens;
        this.cadCompra = cadCompra; 
    }
    
    public CadastroItensCompra() {
        initComponents();
        comboProduto.setModel(new DefaultComboBoxModel(new DAOProduto().consultarProdutos().toArray()));
        this.setLocationRelativeTo(null);
    }
    
    public void limpaTela(){
        campoQuantidade.setText("");
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        comboProduto = new javax.swing.JComboBox<>();
        labelProduto = new javax.swing.JLabel();
        labelQuantidade = new javax.swing.JLabel();
        campoQuantidade = new javax.swing.JTextField();
        botaoCancelar = new javax.swing.JButton();
        botaoIncluir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastrar Itens na Compra");

        comboProduto.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        labelProduto.setText("Produto");

        labelQuantidade.setText("Quantidade");

        botaoCancelar.setText("Cancelar");
        botaoCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoCancelarActionPerformed(evt);
            }
        });

        botaoIncluir.setText("Incluir");
        botaoIncluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoIncluirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(comboProduto, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(campoQuantidade)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelProduto)
                            .addComponent(labelQuantidade))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 197, Short.MAX_VALUE)
                        .addComponent(botaoIncluir)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(botaoCancelar)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(labelProduto)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(comboProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelQuantidade)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(campoQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botaoIncluir)
                    .addComponent(botaoCancelar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void campoQuantidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoQuantidadeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoQuantidadeActionPerformed

    private void botaoIncluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoIncluirActionPerformed
        ItensCompra itenscompra = new ItensCompra();
        boolean inserir = true;
        try{
            itenscompra.setQuantidade(Double.parseDouble(campoQuantidade.getText()));
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "Erro no salário!");
            campoQuantidade.requestFocus();
            inserir = false;
        }
        itenscompra.setProduto((Produto) comboProduto.getSelectedItem());
        
        if(inserir){
            listaItens.add(itenscompra);
        }
        cadCompra.valor += itenscompra.getProduto().getPreco() * itenscompra.getQuantidade();
        cadCompra.alteraValor();
        limpaTela();
    }//GEN-LAST:event_botaoIncluirActionPerformed

    private void botaoCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoCancelarActionPerformed
        this.dispose();
    }//GEN-LAST:event_botaoCancelarActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoCancelar;
    private javax.swing.JButton botaoIncluir;
    private javax.swing.JTextField campoQuantidade;
    private javax.swing.JComboBox<String> comboProduto;
    private javax.swing.JLabel labelProduto;
    private javax.swing.JLabel labelQuantidade;
    // End of variables declaration//GEN-END:variables
}
